# vim: set ts=2 sw=2 tw=0 fo=cnqoj
# Goreleaser configuration

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/b3scalectl
    env:
      - CGO_ENABLED=0
    id: "b3scalectl"
    binary: b3scalectl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "github.com/b3scale/b3scale/pkg/config.Version={{ .Version }}" -X "github.com/b3scale/b3scale/pkg/config.Build={{ .Commit }}"

  - main: ./cmd/b3scalenoded
    env:
      - CGO_ENABLED=0
    id: "b3scalenoded"
    binary: b3scalenoded 
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "github.com/b3scale/b3scale/pkg/config.Version={{ .Version }}" -X "github.com/b3scale/b3scale/pkg/config.Build={{ .Commit }}"

  - main: ./cmd/b3scaleagent
    env:
      - CGO_ENABLED=0
    id: "b3scaleagent"
    binary: b3scaleagent
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "github.com/b3scale/b3scale/pkg/config.Version={{ .Version }}" -X "github.com/b3scale/b3scale/pkg/config.Build={{ .Commit }}"

  - main: ./cmd/b3scaled
    env:
      - CGO_ENABLED=0
    id: "b3scaled"
    binary: b3scaled
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "github.com/b3scale/b3scale/pkg/config.Version={{ .Version }}" -X "github.com/b3scale/b3scale/pkg/config.Build={{ .Commit }}"

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" 
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
